name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Write TMDB_KEY to .env
      run: echo 'TMDB_KEY={{ secrets.TMDB_KEY }}' > .env
    - uses: subosito/flutter-action@v1
    - run: flutter test